/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TSPSERVER_H_RPCGEN
#define _TSPSERVER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SERVERPROG 0x20000002
#define SERVERVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SERVTRAVERSE 1
extern  int * servtraverse_1(char **, CLIENT *);
extern  int * servtraverse_1_svc(char **, struct svc_req *);
extern int serverprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SERVTRAVERSE 1
extern  int * servtraverse_1();
extern  int * servtraverse_1_svc();
extern int serverprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TSPSERVER_H_RPCGEN */
